### ISSUE TITLE
Confirmation of module "zero"

### ISSUE THREAD

**Issue by jayenliao** [Yura52/tabular-dl-revisiting-models#26] opened 2022-05-07 08:50 UTC
Hello,

Thank you for sharing your excellent work!

When I rerun the code, many different attribute errors about zero raised, such as

- AttributeError: module 'zero' has no attribute 'set_randomness'
- AttributeError: module 'zero' has no attribute 'Timer'
- AttributeError: module 'zero' has no attribute 'Stream'

It seems that I am using different 'zero' module, which was installed by pip3 install zero (the version is 0.9.1)
Would you please let me know if zero that you use is [this one](https://pypi.org/project/zero/) and its version (not mentioned in requirement.txt)?

Thank you very much!

**Comment by Yura52** [comment] 2022-05-07 09:11
Hello @jayenliao ,

I highly recommend following the original instruction for setting up the environment: [link](https://github.com/Yura52/tabular-dl-revisiting-models#3-setup-the-environment). In particular, the `zero` module will be installed from `requirements.txt` as `pip install libzero==0.0.3.dev7`. The documentation for this specific version is available here: [link](https://yura52.github.io/zero/0.0.3.dev7/) (JFYI: the more recent versions of `zero` have significantly different API). The PyPi link for the package: [link](https://pypi.org/project/libzero/).

Feel free to reopen the issue if the issue is not solved.

**Closed by Yura52** 2022-05-07 09:11 UTC
